package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tessellator/go-sanity/sanity"
)

var _ resource.Resource = &ProjectTokenResource{}
var _ resource.ResourceWithImportState = &ProjectTokenResource{}

func NewProjectTokenResource() resource.Resource {
	return &ProjectTokenResource{}
}

type ProjectTokenResource struct {
	client *sanity.Client
}

type ProjectTokenResourceModel struct {
	Id       types.String `tfsdk:"id"`
	Project  types.String `tfsdk:"project"`
	Label    types.String `tfsdk:"label"`
	RoleName types.String `tfsdk:"role_name"`
	Key      types.String `tfsdk:"key"`
}

func (r *ProjectTokenResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_token"
}

func (r *ProjectTokenResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Provides a Sanity project token. The token key is a sensitive value that can be used to make authenticated requests against the Sanity HTTP API.",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The unique token ID generated by Sanity.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The project ID, which you can find at the top of the project page in Sanity.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"label": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "A descriptive label for the token.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"role_name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The role name that indicates which permissions are assigned to the token. For a free account, valid values are `viewer`, `editor`, and `deploy-studio`.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"key": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				MarkdownDescription: "The token value. This value can be used for making authenticated requests against the API with the permissions indicated by the role name.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *ProjectTokenResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	clients, ok := req.ProviderData.(*ProviderClients)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = clients.SanityClient
}

func (r *ProjectTokenResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *ProjectTokenResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tokenResp, err := r.client.Projects.CreateProjectToken(ctx, data.Project.ValueString(), &sanity.CreateProjectTokenRequest{
		Label:    data.Label.ValueString(),
		RoleName: data.RoleName.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	data.Id = types.StringValue(tokenResp.Id)
	data.Key = types.StringValue(tokenResp.Key)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectTokenResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *ProjectTokenResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	if data.Id.IsNull() {
		resp.Diagnostics.AddError("Entry id is null", "Entry id is null")
		return
	}
	if data.Project.IsNull() {
		resp.Diagnostics.AddError("Project is null", "Project is null")
		return
	}

	tokens, err := r.client.Projects.ListProjectTokens(ctx, data.Project.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	var token sanity.ProjectToken
	found := false

	for _, t := range tokens {
		if t.Id == data.Id.ValueString() {
			token = t
			found = true
			break
		}
	}
	if !found {
		resp.Diagnostics.AddError("project token not found", "project token not found")
		return
	}

	data.Label = types.StringValue(token.Label)
	// we cannot actually capture the delta on role_name because it is an
	// ephemeral value... it is only used to populate roles and is not stored as
	// part of the actual resource on Sanity's side

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectTokenResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Provider Error", "Update is not supported on project tokens")
}

func (r *ProjectTokenResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *ProjectTokenResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	if data.Id.IsNull() {
		resp.Diagnostics.AddError("Entry id is null", "Entry id is null")
		return
	}
	if data.Project.IsNull() {
		resp.Diagnostics.AddError("Project is null", "Project is null")
		return
	}

	_, err := r.client.Projects.DeleteProjectToken(ctx, data.Project.ValueString(), data.Id.ValueString())

	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("entry %s could not be deleted, got error: %s", data.Id.ValueString(), err))
		return
	}
}

func (r *ProjectTokenResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
